export default {
  'app.account.signin.login': 'Log In',
  'app.account.signin.forget': 'Forgot password?',
  'app.account.signin.company': 'Switch enterprise account',
  'app.account.signin.ok': 'OK',
  'app.account.signin.cancel': 'Cancel',
  'app.account.signin.remake': 'You have logged in elsewhere, whether mandatory login?',
  'app.account.bindPhone.get': 'GET',
  'app.account.bindPhone.submit': 'Confirm',
  'app.account.bindPhone.jump': 'Skip',
  'app.account.bindPhone.remark': 'After registering your phone,you can log on using mobile number and password,you can retrieve your password using mobile number.',
  'app.account.changePwd.submit': 'Confirm',
  'app.account.forget.get': 'GET',
  'app.account.forget.find': 'Reset password',
  'app.account.forget.remark': 'You have not yet registered your phone, please contact the administrator to reset your password.',
  'app.account.signinCom.submit': 'Log In',
  'app.account.signinCom.remark': "If you don't know the Corp ID, please contact your training manager.",
  'inputTel': 'Enter mobile number',
  'inputId': 'Enter Corp ID',
  'inputAccount': 'Enter account',
  'inputPwd': 'Enter password',
  'inputCode': 'Enter captcha',
  'app.account.changePwd.inputPwd': 'Enter new password',
  'app.account.changePwd.inputPwdAgain': 'Confirm new password',
  'app.account.signin.title': 'Login',
  'app.account.bindPhone.title': 'Registered mobile number',
  'app.account.forget.title': 'Forgot password?',
  'app.account.changePwd.title': 'Password',
  'app.account.toast': 'Please fill in complete information',
  'app.account.bindID': 'The phone number is not bound to any enterprise ID',
  'app.account.changeSuccess': 'Modified successfully',
  'app.account.difference': 'The passwords entered did not match',
  'app.account.PhoneWrong': 'The phone number format is incorrect',
};

