export default {
  'app.account.signin.login': '登 录',
  'app.account.signin.forget': '忘 记 密 码？',
  'app.account.signin.ok': '确定',
  'app.account.signin.cancel': '取消',
  'app.account.signin.remake': '该账户已经登录，是否强制登录',
  'app.account.signin.company': '使用企业账号登录',
  'app.account.bindPhone.get': '获取验证码',
  'app.account.bindPhone.submit': '确 定',
  'app.account.bindPhone.jump': '跳 过',
  'app.account.bindPhone.remark': '您还未绑定手机，绑定手机可凭手机号和密码登录。如您将来不慎遗忘密码亦可凭手机重置密码。',
  'app.account.changePwd.submit': '确 认 修 改',
  'app.account.forget.get': '获取验证码',
  'app.account.forget.find': '找 回 密 码',
  'app.account.forget.remark': '若未绑定手机号，请联系管理员进行重置密码',
  'app.account.signinCom.submit': '登 录',
  'app.account.signinCom.remark': '您如果不确定您的企业ID，请联系贵司培训管理员',
  'inputTel': '请输入手机号',
  'inputId': '请输入企业ID',
  'inputAccount': '请输入用户名',
  'inputPwd': '请输入密码',
  'inputCode': '请输入验证码',
  'app.account.changePwd.inputPwd': '请输入新密码',
  'app.account.changePwd.inputPwdAgain': '请再次输入新密码',
  'app.account.signin.title': '登录',
  'app.account.bindPhone.title': '绑定手机',
  'app.account.forget.title': '忘记密码',
  'app.account.changePwd.title': '修改密码',
  'app.account.toast': '请将信息填写完整',
  'app.account.bindID': '该手机号还未绑定企业ID',
  'app.account.changeSuccess': '修改成功',
  'app.account.difference': '两次密码输入不一致',
  'app.account.PhoneWrong': '手机号不正确，请检查',
};

