// fetch announcement
export const FETCH_ANNOUNCEMENT_LIST_REQUEST = 'FETCH_ANNOUNCEMENT_LIST_REQUEST';
export const FETCH_ANNOUNCEMENT_LIST_FAILURE = 'FETCH_ANNOUNCEMENT_LIST_FAILURE';
export const FETCH_ANNOUNCEMENT_LIST_SUCCESS = 'FETCH_ANNOUNCEMENT_LIST_SUCCESS';

export const FETCH_ANNOUNCEMENT_DETAIL_REQUEST = 'FETCH_ANNOUNCEMENT_DETAIL_REQUEST';
export const FETCH_ANNOUNCEMENT_DETAIL_FAILURE = 'FETCH_ANNOUNCEMENT_DETAIL_FAILURE';
export const FETCH_ANNOUNCEMENT_DETAIL_SUCCESS = 'FETCH_ANNOUNCEMENT_DETAIL_SUCCESS';

export const FETCH_ANNOUNCEMENT_COMMENTS_COUNT_REQUEST = 'FETCH_ANNOUNCEMENT_COMMENTS_COUNT_REQUEST';
export const FETCH_ANNOUNCEMENT_COMMENTS_COUNT_FAILURE = 'FETCH_ANNOUNCEMENT_COMMENTS_COUNT_FAILURE';
export const FETCH_ANNOUNCEMENT_COMMENTS_COUNT_SUCCESS = 'FETCH_ANNOUNCEMENT_COMMENTS_COUNT_SUCCESS';

export const SUBMIT_ANNOUNCEMENT_COMMENT_REQUEST = 'SUBMIT_ANNOUNCEMENT_COMMENT_REQUEST';
export const SUBMIT_ANNOUNCEMENT_COMMENT_FAILURE = 'SUBMIT_ANNOUNCEMENT_COMMENT_FAILURE';
export const SUBMIT_ANNOUNCEMENT_COMMENT_SUCCESS = 'SUBMIT_ANNOUNCEMENT_COMMENT_SUCCESS';

export const FETCH_ANNOUNCEMENT_COMMENTS_REQUEST = 'FETCH_ANNOUNCEMENT_COMMENTS_REQUEST';
export const FETCH_ANNOUNCEMENT_COMMENTS_FAILURE = 'FETCH_ANNOUNCEMENT_COMMENTS_FAILURE';
export const FETCH_ANNOUNCEMENT_COMMENTS_SUCCESS = 'FETCH_ANNOUNCEMENT_COMMENTS_SUCCESS';

export const FETCH_ANNOUNCEMENT_LIKE_REQUEST = 'FETCH_ANNOUNCEMENT_LIKE_REQUEST';
export const FETCH_ANNOUNCEMENT_LIKE_FAILURE = 'FETCH_ANNOUNCEMENT_LIKE_FAILURE';
export const FETCH_ANNOUNCEMENT_LIKE_SUCCESS = 'FETCH_ANNOUNCEMENT_LIKE_SUCCESS';

export const RESET_ANNOUNCEMENT_PAGE_LIST = 'RESET_ANNOUNCEMENT_PAGE_LIST';
export const NEXT_ANNOUNCEMENT_PAGE_LIST = 'NEXT_ANNOUNCEMENT_PAGE_LIST';
export const RESET_ANNOUNCEMENT_PAGE_COMMENTS = 'RESET_ANNOUNCEMENT_PAGE_COMMENTS';
export const NEXT_ANNOUNCEMENT_PAGE_COMMENTS = 'NEXT_ANNOUNCEMENT_PAGE_COMMENTS';
