//
export const FETCH_COMMENT_LIST_REQUEST = 'FETCH_COMMENT_LIST_REQUEST';
export const FETCH_COMMENT_LIST_FAILURE = 'FETCH_COMMENT_LIST_FAILURE';
export const FETCH_COMMENT_LIST_SUCCESS = 'FETCH_COMMENT_LIST_SUCCESS';
export const FETCH_COMMENT_LIST_INIT = 'FETCH_COMMENT_LIST_INIT';

//
export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST';
export const FETCH_COMMENT_FAILURE = 'FETCH_COMMENT_FAILURE';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';

//
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';

//
export const ADD_MY_COMMENT = 'ADD_MY_COMMENT';
