export const INIT_COURSE = 'INIT_COURSE';
// fetch course
export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST';
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';

// fetch chapter
export const FETCH_CHAPTER_REQUEST = 'FETCH_CHAPTER_REQUEST';
export const FETCH_CHAPTER_FAILURE = 'FETCH_CHAPTER_FAILURE';
export const FETCH_CHAPTER_SUCCESS = 'FETCH_CHAPTER_SUCCESS';

// fetch chapter
export const FETCH_ASSESSMENT_REQUEST = 'FETCH_ASSESSMENT_REQUEST';
export const FETCH_ASSESSMENT_FAILURE = 'FETCH_ASSESSMENT_FAILURE';
export const FETCH_ASSESSMENT_SUCCESS = 'FETCH_ASSESSMENT_SUCCESS';
export const UPDATE_NODE_URL = 'UPDATE_NODE_URL';

// favor course
export const FACOR_COURSE_REQUEST = 'FACOR_COURSE_REQUEST';
export const FACOR_COURSE_FAILURE = 'FACOR_COURSE_FAILURE';
export const FACOR_COURSE_SUCCESS = 'FACOR_COURSE_SUCCESS';

// arrange course
export const ARRANGE_COURSE_REQUEST = 'ARRANGE_COURSE_REQUEST';
export const ARRANGE_COURSE_FAILURE = 'ARRANGE_COURSE_FAILURE';
export const ARRANGE_COURSE_SUCCESS = 'ARRANGE_COURSE_SUCCESS';

export const SET_NODE_READ = 'SET_NODE_READ';
