// required
export const INIT_REQUIRED_DISTRIBUTION = 'INIT_REQUIRED_DISTRIBUTION';
export const FETCH_REQUIRED_COURSE_SUCCESS = 'FETCH_REQUIRED_COURSE_SUCCESS';
export const PAGINATE_REQUIRED_COURSE_SUCCESS = 'PAGINATE_REQUIRED_COURSE_SUCCESS';
export const SELECT_REQUIRED_COURSE = 'SELECT_REQUIRED_COURSE';
export const UNSELECT_REQUIRED_COURSE = 'UNSELECT_REQUIRED_COURSE';

export const FETCH_COURSE_USER_SUCCESS = 'FETCH_COURSE_USER_SUCCESS';
export const PAGINATE_COURSE_USER_SUCCESS = 'PAGINATE_COURSE_USER_SUCCESS';
export const SELECT_COURSE_USERS = 'SELECT_COURSE_USERS';
export const SELECT_COURSE_USER = 'SELECT_COURSE_USER';
export const UNSELECT_COURSE_USER = 'UNSELECT_COURSE_USER';
export const UNSELECT_COURSE_USERS = 'UNSELECT_COURSE_USERS';

export const SELECT_DISTRIBUTION_DEPARTMENT = 'SELECT_DISTRIBUTION_DEPARTMENT';
export const SELECT_DISTRIBUTION_CHILD_DEPARTMENT = 'SELECT_DISTRIBUTION_CHILD_DEPARTMENT';
export const FETCH_DISTRIBUTION_DEPARTMENT = 'FETCH_DISTRIBUTION_DEPARTMENT';

// live
export const INIT_LIVE_DISTRIBUTION = 'INIT_LIVE_DISTRIBUTION';
export const FETCH_DISTRIBUTION_LIVE_SUCCESS = 'FETCH_LIVE_COURSE_SUCCESS';
export const PAGINATE_DISTRIBUTION_LIVE_SUCCESS = 'PAGINATE_LIVE_COURSE_SUCCESS';
export const SELECT_DISTRIBUTION_LIVE = 'SELECT_LIVE_COURSE';
export const UNSELECT_DISTRIBUTION_LIVE = 'UNSELECT_LIVE_COURSE';

export const FETCH_LIVE_USER_SUCCESS = 'FETCH_LIVE_USER_SUCCESS';
export const PAGINATE_LIVE_USER_SUCCESS = 'PAGINATE_LIVE_USER_SUCCESS';
export const SELECT_LIVE_USERS = 'SELECT_LIVE_USERS';
export const SELECT_LIVE_USER = 'SELECT_LIVE_USER';
export const UNSELECT_LIVE_USERS = 'UNSELECT_LIVE_USERS';
export const UNSELECT_LIVE_USER = 'UNSELECT_LIVE_USER';

export const SELECT_LIVE_DISTRIBUTION_DEPARTMENT = 'SELECT_DEPARTMENT_FOR_LIVE_DISTRIBUTION';
export const SELECT_LIVE_DISTRIBUTION_CHILD_DEPARTMENT = 'SELECT_CHILD_DEPARTMENT_FOR_LIVE_DISTRIBUTION';
export const FETCH_DEPARTMENT_FOR_LIVE_DISTRIBUTION = 'FETCH_DEPARTMENT_FOR_LIVE_DISTRIBUTION';
