// fetch electives
export const FETCH_ELECTIVES_NEW_REQUEST = 'FETCH_ELECTIVES_NEW_REQUEST';
export const FETCH_ELECTIVES_NEW_FAILURE = 'FETCH_ELECTIVES_NEW_FAILURE';
export const FETCH_ELECTIVES_NEW_SUCCESS = 'FETCH_ELECTIVES_NEW_SUCCESS';
export const FETCH_ELECTIVES_HOT_REQUEST = 'FETCH_ELECTIVES_HOT_REQUEST';
export const FETCH_ELECTIVES_HOT_FAILURE = 'FETCH_ELECTIVES_HOT_FAILURE';
export const FETCH_ELECTIVES_HOT_SUCCESS = 'FETCH_ELECTIVES_HOT_SUCCESS';
export const FETCH_ELECTIVES_REFRESH_NEW = 'FETCH_ELECTIVES_REFRESH_NEW';
export const FETCH_ELECTIVES_REFRESH_HOT = 'FETCH_ELECTIVES_REFRESH_HOT';


export const FETCH_ELECTIVES_ACTIVE = 'FETCH_ELECTIVES_ACTIVE';
