// fetch exams
export const FETCH_EXAMS_INFO_REQUEST = 'FETCH_EXAMS_INFO_REQUEST';
export const FETCH_EXAMS_INFO_FAILURE = 'FETCH_EXAMS_INFO_FAILURE';
export const FETCH_EXAMS_INFO_SUCCESS = 'FETCH_EXAMS_INFO_SUCCESS';

export const FETCH_EXAMS_HISTORY_REQUEST = 'FETCH_EXAMS_HISTORY_REQUEST';
export const FETCH_EXAMS_HISTORY_FAILURE = 'FETCH_EXAMS_HISTORY_FAILURE';
export const FETCH_EXAMS_HISTORY_SUCCESS = 'FETCH_EXAMS_HISTORY_SUCCESS';

export const FETCH_EXAMS_RANK_REQUEST = 'FETCH_EXAMS_RANK_REQUEST';
export const FETCH_EXAMS_RANK_FAILURE = 'FETCH_EXAMS_RANK_FAILURE';
export const FETCH_EXAMS_RANK_SUCCESS = 'FETCH_EXAMS_RANK_SUCCESS';

export const FETCH_EXAMS_PROCESS_REQUEST = 'FETCH_EXAMS_PROCESS_REQUEST';
export const FETCH_EXAMS_PROCESS_FAILURE = 'FETCH_EXAMS_PROCESS_FAILURE';
export const FETCH_EXAMS_PROCESS_SUCCESS = 'FETCH_EXAMS_PROCESS_SUCCESS';

export const RESET_EXAMS_PROCESS_SUBMIT = 'RESET_EXAMS_PROCESS_SUBMIT';
export const FETCH_EXAMS_PROCESS_SUBMIT_REQUEST = 'FETCH_EXAMS_PROCESS_SUBMIT_REQUEST';
export const FETCH_EXAMS_PROCESS_SUBMIT_FAILURE = 'FETCH_EXAMS_PROCESS_SUBMIT_FAILURE';
export const FETCH_EXAMS_PROCESS_SUBMIT_SUCCESS = 'FETCH_EXAMS_PROCESS_SUBMIT_SUCCESS';

export const RESET_EXAMS_PROCESS_SUBMIT_BEST = 'RESET_EXAMS_PROCESS_SUBMIT_BEST';
export const FETCH_EXAMS_PROCESS_SUBMIT_BEST_REQUEST = 'FETCH_EXAMS_PROCESS_SUBMIT_BEST_REQUEST';
export const FETCH_EXAMS_PROCESS_SUBMIT_BEST_FAILURE = 'FETCH_EXAMS_PROCESS_SUBMIT_BEST_FAILURE';
export const FETCH_EXAMS_PROCESS_SUBMIT_BEST_SUCCESS = 'FETCH_EXAMS_PROCESS_SUBMIT_BEST_SUCCESS';

export const FETCH_EXAMS_REVIEW_REQUEST = 'FETCH_EXAMS_REVIEW_REQUEST';
export const FETCH_EXAMS_REVIEW_FAILURE = 'FETCH_EXAMS_REVIEW_FAILURE';
export const FETCH_EXAMS_REVIEW_SUCCESS = 'FETCH_EXAMS_REVIEW_SUCCESS';

export const FETCH_EXAMS_PLAN_REQUEST = 'FETCH_EXAMS_PLAN_REQUEST';
export const FETCH_EXAMS_PLAN_FAILURE = 'FETCH_EXAMS_PLAN_FAILURE';
export const FETCH_EXAMS_PLAN_SUCCESS = 'FETCH_EXAMS_PLAN_SUCCESS';
