// fetch live
export const FETCH_LIVE_MEETING_REQUEST = 'FETCH_LIVE_MEETING_REQUEST';
export const FETCH_LIVE_MEETING_FAILURE = 'FETCH_LIVE_MEETING_FAILURE';
export const FETCH_LIVE_MEETING_SUCCESS = 'FETCH_LIVE_MEETING_SUCCESS';

export const FETCH_LIVE_PUBLICS_REQUEST = 'FETCH_LIVE_PUBLICS_REQUEST';
export const FETCH_LIVE_PUBLICS_FAILURE = 'FETCH_LIVE_PUBLICS_FAILURE';
export const FETCH_LIVE_PUBLICS_SUCCESS = 'FETCH_LIVE_PUBLICS_SUCCESS';

export const FETCH_LIVE_OWNPURCHASE_REQUEST = 'FETCH_LIVE_OWNPURCHASE_REQUEST';
export const FETCH_LIVE_OWNPURCHASE_FAILURE = 'FETCH_LIVE_OWNPURCHASE_FAILURE';
export const FETCH_LIVE_OWNPURCHASE_SUCCESS = 'FETCH_LIVE_OWNPURCHASE_SUCCESS';

export const FETCH_LIVE_ACTIVE = 'FETCH_LIVE_ACTIVE';
export const FETCH_LIVE_NEW = 'FETCH_LIVE_NEW';

export const FETCH_LIVE_HISTORY_SUCCESS = 'FETCH_LIVE_HISTORY_SUCCESS';
export const FETCH_LIVE_HISTORY_FAILURE = 'FETCH_LIVE_HISTORY_FAILURE';

export const FETCH_LIVE_URL_REQUEST = 'FETCH_LIVE_URL_REQUEST';
export const FETCH_LIVE_URL_SUCCESS = 'FETCH_LIVE_URL_SUCCESS';

export const FETCH_CODE_REQUEST = 'FETCH_CODE_REQUEST';
export const FETCH_CODE_SUCCESS = 'FETCH_CODE_SUCCESS';

export const FETCH_NOTIFICATION_REQUEST = 'FETCH_NOTIFICATION_REQUEST';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';

export const FETCH_RECORD_URL_REQUEST = 'FETCH_RECORD_URL_REQUEST';
export const FETCH_RECORD_URL_SUCCESS = 'FETCH_RECORD_URL_SUCCESS';

export const INIT_LIVE = 'INIT_LIVE';
