export const FETCH_CLASSIFICATIONS_PRODUCTS_REQUEST = 'FETCH_CLASSIFICATIONS_PRODUCTS_REQUEST';
export const FETCH_CLASSIFICATIONS_PRODUCTS_FAILURE = 'FETCH_CLASSIFICATIONS_PRODUCTS_FAILURE';
export const FETCH_CLASSIFICATIONS_PRODUCTS_SUCCESS = 'FETCH_CLASSIFICATIONS_PRODUCTS_SUCCESS';

export const FETCH_RECOMMEND_PRODUCTS_REQUEST = 'FETCH_RECOMMEND_PRODUCTS_REQUEST';
export const FETCH_RECOMMEND_PRODUCTS_SUCCESS = 'FETCH_RECOMMEND_PRODUCTS_SUCCESS';
export const FETCH_RECOMMEND_PRODUCTS_FAILURE = 'FETCH_RECOMMEND_PRODUCTS_FAILURE';

export const FETCH_MALL_HOME_STATS_REQUEST = 'FETCH_MALL_HOME_STATS_REQUEST';
export const FETCH_MALL_HOME_STATS_SUCCESS = 'FETCH_MALL_HOME_STATS_SUCCESS';
export const FETCH_MALL_HOME_STATS_FAILURE = 'FETCH_MALL_HOME_STATS_FAILURE';

export const SET_MALL_HOME_CLOSE_MARK = 'SET_MALL_HOME_CLOSE_MARK';

export const FETCH_MALL_MORE_CLASSIFICATION_REQUEST = 'FETCH_MALL_MORE_CLASSIFICATION_REQUEST';
export const FETCH_MALL_MORE_CLASSIFICATION_SUCCESS = 'FETCH_MALL_MORE_CLASSIFICATION_SUCCESS';
export const FETCH_MALL_MORE_CLASSIFICATION_FAILURE = 'FETCH_MALL_MORE_CLASSIFICATION_FAILURE';

export const FETCH_MALL_MORE_PRODUCTS_REQUEST = 'FETCH_MALL_MORE_PRODUCTS_REQUEST';
export const FETCH_MALL_MORE_PRODUCTS_SUCCESS = 'FETCH_MALL_MORE_PRODUCTS_SUCCESS';
export const FETCH_MALL_MORE_PRODUCTS_FAILURE = 'FETCH_MALL_MORE_PRODUCTS_FAILURE';
export const RESET_MALL_MORE_PAGEINFO = 'RESET_MALL_MORE_PAGEINFO';
export const SET_MALL_MORE_NEXT_PAGE = 'SET_MALL_MORE_NEXT_PAGE';
export const SET_MALL_MORE_ACTIVE_CLASSIFICATION = 'SET_MALL_MORE_ACTIVE_CLASSIFICATION';

export const FETCH_LIVE_PRODUCTS_REQUEST = 'FETCH_LIVE_PRODUCTS_REQUEST';
export const FETCH_LIVE_PRODUCTS_SUCCESS = 'FETCH_LIVE_PRODUCTS_SUCCESS';
export const FETCH_LIVE_PRODUCTS_FAILURE = 'FETCH_LIVE_PRODUCTS_FAILURE';


export const FETCH_MALL_BANNER_REQUEST = 'FETCH_MALL_BANNER_REQUEST';
export const FETCH_MALL_BANNER_SUCCESS = 'FETCH_MALL_BANNER_SUCCESS';
export const FETCH_MALL_BANNER_FAILURE = 'FETCH_MALL_BANNER_FAILURE';



