export const FETCH_NEW_MESSAGE_REQUEST = 'FETCH_NEW_MESSAGE_REQUEST';
export const FETCH_NEW_MESSAGE_FAILURE = 'FETCH_NEW_MESSAGE_FAILURE';
export const FETCH_NEW_MESSAGE_SUCCESS = 'FETCH_NEW_MESSAGE_SUCCESS';
