// order list
export const FETCH_ORDER_TITLE_ACTIVE = 'FETCH_ORDER_TITLE_ACTIVE';
export const FETCH_ORDER_CLEARUP_ACTIVE = 'FETCH_ORDER_CLEARUP_ACTIVE';
export const FETCH_ORDER_LIST_REQUEST = 'FETCH_ORDER_LIST_REQUEST';
export const FETCH_ORDER_LIST_FAILURE = 'FETCH_ORDER_LIST_FAILURE';
export const FETCH_ORDER_LIST_SUCCESS = 'FETCH_ORDER_LIST_SUCCESS';

// order confirm
export const FETCH_ORDER_CONFIRM_REQUEST = 'FETCH_ORDER_CONFIRM_REQUEST';
export const FETCH_ORDER_CONFIRM_FAILURE = 'FETCH_ORDER_CONFIRM_FAILURE';
export const FETCH_ORDER_CONFIRM_SUCCESS = 'FETCH_ORDER_CONFIRM_SUCCESS';
export const FETCH_ORDER_SUBMIT_REQUEST = 'FETCH_ORDER_SUBMIT_REQUEST';
export const FETCH_ORDER_SUBMIT_FAILURE = 'FETCH_ORDER_SUBMIT_FAILURE';
export const FETCH_ORDER_SUBMIT_SUCCESS = 'FETCH_ORDER_SUBMIT_SUCCESS';


// order detail
export const FETCH_ORDER_DETAIL_REQUEST = 'FETCH_ORDER_DETAIL_REQUEST';
export const FETCH_ORDER_DETAIL_FAILURE = 'FETCH_ORDER_DETAIL_FAILURE';
export const FETCH_ORDER_DETAIL_SUCCESS = 'FETCH_ORDER_DETAIL_SUCCESS';
