// fetch PAYMENT
export const FETCH_PAYMENT_ORDER_REQUEST = 'FETCH_PAYMENT_ORDER_REQUEST';
export const FETCH_PAYMENT_ORDER_FAILURE = 'FETCH_PAYMENT_ORDER_FAILURE';
export const FETCH_PAYMENT_ORDER_SUCCESS = 'FETCH_PAYMENT_ORDER_SUCCESS';

export const SUBMIT_PAYMENT_ALIPAY_REQUEST = 'SUBMIT_PAYMENT_ALIPAY_REQUEST';
export const SUBMIT_PAYMENT_ALIPAY_FAILURE = 'SUBMIT_PAYMENT_ALIPAY_FAILURE';
export const SUBMIT_PAYMENT_ALIPAY_SUCCESS = 'SUBMIT_PAYMENT_ALIPAY_SUCCESS';

export const SUBMIT_PAYMENT_WCPAY_REQUEST = 'SUBMIT_PAYMENT_WCPAY_REQUEST';
export const SUBMIT_PAYMENT_WCPAY_FAILURE = 'SUBMIT_PAYMENT_WCPAY_FAILURE';
export const SUBMIT_PAYMENT_WCPAY_SUCCESS = 'SUBMIT_PAYMENT_WCPAY_SUCCESS';

export const SUBMIT_PAYMENT_ENTERPRISE_PAY_REQUEST = 'SUBMIT_PAYMENT_ENTERPRISE_PAY_REQUEST';
export const SUBMIT_PAYMENT_ENTERPRISE_PAY_FAILURE = 'SUBMIT_PAYMENT_ENTERPRISE_PAY_FAILURE';
export const SUBMIT_PAYMENT_ENTERPRISE_PAY_SUCCESS = 'SUBMIT_PAYMENT_ENTERPRISE_PAY_SUCCESS';

export const SUBMIT_PAYMENT_VERIFICATION_CODE_REQUEST = 'SUBMIT_PAYMENT_VERIFICATION_CODE_REQUEST';
export const SUBMIT_PAYMENT_VERIFICATION_CODE_FAILURE = 'SUBMIT_PAYMENT_VERIFICATION_CODE_FAILURE';
export const SUBMIT_PAYMENT_VERIFICATION_CODE_SUCCESS = 'SUBMIT_PAYMENT_VERIFICATION_CODE_SUCCESS';

export const FETCH_PAYMENT_ENTERPRISE_ORDER_REQUEST = 'FETCH_PAYMENT_ENTERPRISE_ORDER_REQUEST';
export const FETCH_PAYMENT_ENTERPRISE_ORDER_FAILURE = 'FETCH_PAYMENT_ENTERPRISE_ORDER_FAILURE';
export const FETCH_PAYMENT_ENTERPRISE_ORDER_SUCCESS = 'FETCH_PAYMENT_ENTERPRISE_ORDER_SUCCESS';

export const FETCH_PAYMENT_ORDER_ITEM_NUMBER_REQUEST = 'FETCH_PAYMENT_ORDER_ITEM_NUMBER_REQUEST';
export const FETCH_PAYMENT_ORDER_ITEM_NUMBER_FAILURE = 'FETCH_PAYMENT_ORDER_ITEM_NUMBER_FAILURE';
export const FETCH_PAYMENT_ORDER_ITEM_NUMBER_SUCCESS = 'FETCH_PAYMENT_ORDER_ITEM_NUMBER_SUCCESS';

export const RESET_PAYMENT_VERIFICATION_CODE = 'RESET_PAYMENT_VERIFICATION_CODE';
export const SET_PAYMENT_STATUS = 'SET_PAYMENT_STATUS';
