// fetch plans
export const FETCH_PLANS_ALL_REQUEST = 'FETCH_PLANS_ALL_REQUEST';
export const FETCH_PLANS_ALL_FAILURE = 'FETCH_PLANS_ALL_FAILURE';
export const FETCH_PLANS_ALL_SUCCESS = 'FETCH_PLANS_ALL_SUCCESS';

export const FETCH_PLANS_REQUIRED_REQUEST = 'FETCH_PLANS_REQUIRED_REQUEST';
export const FETCH_PLANS_REQUIRED_FAILURE = 'FETCH_PLANS_REQUIRED_FAILURE';
export const FETCH_PLANS_REQUIRED_SUCCESS = 'FETCH_PLANS_REQUIRED_SUCCESS';

export const FETCH_PLANS_ELECTIVE_REQUEST = 'FETCH_PLANS_ELECTIVE_REQUEST';
export const FETCH_PLANS_ELECTIVE_FAILURE = 'FETCH_PLANS_ELECTIVE_FAILURE';
export const FETCH_PLANS_ELECTIVE_SUCCESS = 'FETCH_PLANS_ELECTIVE_SUCCESS';

export const FETCH_PLANS_OWNPURCHASE_REQUEST = 'FETCH_PLANS_OWNPURCHASE_REQUEST';
export const FETCH_PLANS_OWNPURCHASE_FAILURE = 'FETCH_PLANS_OWNPURCHASE_FAILURE';
export const FETCH_PLANS_OWNPURCHASE_SUCCESS = 'FETCH_PLANS_OWNPURCHASE_SUCCESS';

export const FETCH_PLANS_ACTIVE = 'FETCH_PLANS_ACTIVE';
export const FETCH_PLANS_NEW = 'FETCH_PLANS_NEW';
