// fetch practice
export const FETCH_PRACTICE_REQUEST = 'FETCH_PRACTICE_REQUEST';
export const FETCH_PRACTICE_FAILURE = 'FETCH_PRACTICE_FAILURE';
export const FETCH_PRACTICE_SUCCESS = 'FETCH_PRACTICE_SUCCESS';


export const FETCH_PRACTICE_READ_REQUEST = 'FETCH_PRACTICE_READ_REQUEST';
export const FETCH_PRACTICE_READ_FAILURE = 'FETCH_PRACTICE_READ_FAILURE';
export const FETCH_PRACTICE_READ_SUCCESS = 'FETCH_PRACTICE_READ_SUCCESS';
