// fetch course
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';

// post change password
export const POST_PASSWORD_REQUEST = 'POST_PASSWORD_REQUEST';
export const POST_PASSWORD_FAILURE = 'POST_PASSWORD_FAILURE';
export const POST_PASSWORD_SUCCESS = 'POST_PASSWORD_SUCCESS';

export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST';
export const UPLOAD_PHOTO_FAILURE = 'UPLOAD_PHOTO_FAILURE';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';

