//
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';

export const RESET_SEARCH = 'RESET_SEARCH';
export const NEXT_SEARCH = 'NEXT_SEARCH';