export const ADD_SHOPPING_CART_REQUEST = 'ADD_SHOPPING_CART_REQUEST';
export const ADD_SHOPPING_CART_SUCCESS = 'ADD_SHOPPING_CART_SUCCESS';

export const SHOPPING_CART_COUNT_REQUEST = 'SHOPPING_CART_COUNT_REQUEST';
export const SHOPPING_CART_COUNT_SUCCESS = 'SHOPPING_CART_COUNT_SUCCESS';

export const FETCH_SHOPPING_CART_REQUEST = 'FETCH_SHOPPING_CART_REQUEST';
export const FETCH_SHOPPING_CART_SUCCESS = 'FETCH_SHOPPING_CART_SUCCESS';

export const SETTLEMENT_REQUEST = 'SETTLEMENT_REQUEST';

export const FETCH_CART_BY_QTY_SUCCESS = 'FETCH_CART_BY_QTY_SUCCESS';
export const FETCH_CART_BY_QTY_REQUEST = 'FETCH_CART_BY_QTY_REQUEST';

export const SELECT_CART_REQUEST = 'SELECT_CART_REQUEST';

export const REMOVE_CART_REQUEST = 'REMOVE_CART_REQUEST';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';

export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
