export const FETCH_IS_SIGNED_REQUEST = 'FETCH_IS_SIGNED_REQUEST';
export const FETCH_IS_SIGNED_FAILURE = 'FETCH_IS_SIGNED_FAILURE';
export const FETCH_IS_SIGNED_SUCCESS = 'FETCH_IS_SIGNED_SUCCESS';

export const FETCH_SIGN_LIST_REQUEST = 'FETCH_SIGN_LIST_REQUEST';
export const FETCH_SIGN_LIST_FAILURE = 'FETCH_SIGN_LIST_FAILURE';
export const FETCH_SIGN_LIST_SUCCESS = 'FETCH_SIGN_LIST_SUCCESS';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FROM_HOME = 'SIGN_IN_FROM_HOME';
export const REMOVE_FROM_HOME = 'REMOVE_FROM_HOME';

export const RESET_STATE = 'RESET_STATE';
