// fetch STAFF_TASK
export const FETCH_STAFF_TASK_LIST_REQUEST = 'FETCH_STAFF_TASK_LIST_REQUEST';
export const FETCH_STAFF_TASK_LIST_FAILURE = 'FETCH_STAFF_TASK_LIST_FAILURE';
export const FETCH_STAFF_TASK_LIST_SUCCESS = 'FETCH_STAFF_TASK_LIST_SUCCESS';

export const FETCH_STAFF_TASK_DETAIL_REQUEST = 'FETCH_STAFF_TASK_DETAIL_REQUEST';
export const FETCH_STAFF_TASK_DETAIL_FAILURE = 'FETCH_STAFF_TASK_DETAIL_FAILURE';
export const FETCH_STAFF_TASK_DETAIL_SUCCESS = 'FETCH_STAFF_TASK_DETAIL_SUCCESS';

export const RESET_STAFF_TASK_PAGE = 'RESET_STAFF_TASK_PAGE';
export const NEXT_STAFF_TASK_PAGE = 'NEXT_STAFF_TASK_PAGE';
