//
export const INIT_SURVEY = 'INIT_SURVEY';
export const FETCH_SURVEY_REQUEST = 'FETCH_SURVEY_REQUEST';
export const FETCH_SURVEY_FAILURE = 'FETCH_SURVEY_FAILURE';
export const FETCH_SURVEY_SUCCESS = 'FETCH_SURVEY_SUCCESS';
//
export const SUBMIT_SURVEY_REQUEST = 'SUBMIT_SURVEY_REQUEST';
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE';
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS';
//
export const READ_SURVEY_REQUEST = 'READ_SURVEY_REQUEST';
export const READ_SURVEY_FAILURE = 'READ_SURVEY_FAILURE';
export const READ_SURVEY_SUCCESS = 'READ_SURVEY_SUCCESS';
