// fetch exams
export const FETCH_TRAINING_EXAMS_REQUEST = 'FETCH_TRAINING_EXAMS_REQUEST';
export const FETCH_TRAINING_EXAMS_FAILURE = 'FETCH_TRAINING_EXAMS_FAILURE';
export const FETCH_TRAINING_EXAMS_SUCCESS = 'FETCH_TRAINING_EXAMS_SUCCESS';

export const FETCH_TRAINING_EXAMS_SUBMIT_REQUEST = 'FETCH_TRAINING_EXAMS_SUBMIT_REQUEST';
export const FETCH_TRAINING_EXAMS_SUBMIT_FAILURE = 'FETCH_TRAINING_EXAMS_SUBMIT_FAILURE';
export const FETCH_TRAINING_EXAMS_SUBMIT_SUCCESS = 'FETCH_TRAINING_EXAMS_SUBMIT_SUCCESS';

export const FETCH_TRAINING_PRACTICE_SUBMIT_REQUEST = 'FETCH_TRAINING_PRACTICE_SUBMIT_REQUEST';
export const FETCH_TRAINING_PRACTICE_SUBMIT_FAILURE = 'FETCH_TRAINING_PRACTICE_SUBMIT_FAILURE';
export const FETCH_TRAINING_PRACTICE_SUBMIT_SUCCESS = 'FETCH_TRAINING_PRACTICE_SUBMIT_SUCCESS';
