export * as course from './course';
export * as account from './account';
export * as comment from './comment';
export * as exams from './exams';
export * as plans from './plans';
export * as electives from './electives';
export * as seriesDetail from './series-detail';
export * as surveys from './survey';
export * as practice from './practice';
export * as media from './media';
export * as profile from './profile';
export * as training from './training';
export * as newMessage from './new-message';
export * as signIn from './sign-in';
export * as announcement from './announcement';
export * as mall from './mall';
export * as order from './order';
export * as payment from './payment';
export * as publishElectives from './publish-electives';
export * as previewMall from './preview-mall';
export * as search from './search';
export * as shoppingCart from './shopping-cart';
export * as products from './products';
export * as staffTask from './staffTask';
export * as live from './live';
export actionsInfoCollection from './info-collection';
export studyRoute from './study-route';
